apiVersion: apps/v1
kind: Deployment
metadata:
  name: bai-verdi-operator
  labels:
    app.kubernetes.io/instance: master-test
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: ibm-business-automation-insights
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bai-verdi-operator
  template:
    metadata:
      labels:
        name: bai-verdi-operator
        app.kubernetes.io/component: bai-conversational-assistant
        app: verdi
        app.kubernetes.io/instance: master-test
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/name: ibm-business-automation-insights
      annotations:
        cloudpakId: 94a9c8c358bb43ba8fbdea62e7e166a5
        cloudpakName: IBM Cloud Pak for Business Automation
        cloudpakVersion: 21.0.1
        productChargedContainers: ""
        productCloudpakRatio: "1:1"
        productID: 11117b07ee53456a9cd41fb6751b0759
        productMetric: FREE
        productName: Business Automation Insights - CP4BA - Non Prod
        productVersion: 21.0.1
    spec:
      serviceAccountName: bai-verdi-operator
      containers:
        - name: bai-verdi-operator
          # Replace this with the built image name
          image: XXXXX
          command:
          - verdi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bai-verdi-operator"
          securityContext:
            capabilities:
              drop:
                - all
      imagePullSecrets:
      # Replace this with the secret name
      - name: XXXXX
