apiVersion: v1
kind: ServiceAccount
metadata:
  name: bai-verdi-operator
  labels:
    app.kubernetes.io/instance: master-test
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: ibm-business-automation-insights
