apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verdis.verdi.ibm.com
  labels:
    app.kubernetes.io/instance: master-test
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: ibm-business-automation-insights
spec:
  group: verdi.ibm.com
  names:
    kind: Verdi
    listKind: VerdiList
    plural: verdis
    singular: verdi
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Verdi is the Schema for the verdis API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VerdiSpec defines the desired state of Verdi
            properties:
              acceptlicense:
                type: boolean
              cp4acrprefix:
                type: string
              defaultsossecretpath:
                type: string
              espassword:
                type: string
              esurl:
                type: string
              esusername:
                type: string
              hostname:
                type: string
              imagepullsecretname:
                type: string
              imagerepository:
                type: string
              imagetag:
                type: string
              localvolumepath:
                type: string
              loglevelauthutils:
                type: string
              loglevelbase:
                type: string
              loglevelgetcredentials:
                type: string
              loglevelops:
                type: string
              loglevels3selectiondata:
                type: string
              pvstoragetype:
                type: string
              registerconfigs:
                type: boolean
              runseederassidecar:
                type: boolean
              servercertpath:
                type: string
              serverkeypath:
                type: string
              shows3selectiondata:
                type: boolean
              size:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                format: int32
                type: integer
              ssnenabled:
                type: string
              ssoclientid:
                type: string
              ssoclientsecret:
                type: string
              umsclientid:
                type: string
              umsclientsecret:
                type: string
              umsenabled:
                type: boolean
              umshost:
                type: string
              verdiseederimage:
                type: string
              verdiserverimage:
                type: string
              webappauthnoauthenabled:
                type: boolean
              webapptabsexplorerenabled:
                type: string
              webclientimage:
                type: string
            required:
            - acceptlicense
            - size
            type: object
          status:
            description: VerdiStatus defines the observed state of Verdi
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
